apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: store
spec:
  clusterIP: None
  ports:
    - port: 50055
      protocol: TCP
      targetPort: 50055
      name: store
  selector:
    app: store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: store
        ports:
        - containerPort: 50055
          protocol: TCP
          name: http
      - name: etcd
        image: gcr.io/etcd-development/etcd@sha256:56aa454c329505b221216a60647ab315bf87c5bafe1ffe81c0af9014b496788a
        imagePullPolicy: IfNotPresent
