apiVersion: skaffold/v2beta26
kind: Config
requires:
- path: ./store/storeapis
- path: ./handler/sagahandlerapis
- path: ./tracer/sagatracerapis
- path: ./state/sagastateapis
- path: ./processor/sagaprocessorapis
- path: ./gateway/sagagatewayapis
