// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: sagaprocessorapis/v1/processorapis.proto

package v1

import (
	v1 "github.com/awe76/saga/api/sagatransactionapis/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workflow *v1.Workflow `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Payload  string       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sagaprocessorapis_v1_processorapis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sagaprocessorapis_v1_processorapis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_sagaprocessorapis_v1_processorapis_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteWorkflowRequest) GetWorkflow() *v1.Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *v1.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sagaprocessorapis_v1_processorapis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sagaprocessorapis_v1_processorapis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_sagaprocessorapis_v1_processorapis_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteWorkflowResponse) GetState() *v1.State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_sagaprocessorapis_v1_processorapis_proto protoreflect.FileDescriptor

var file_sagaprocessorapis_v1_processorapis_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x61, 0x67, 0x61, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x61, 0x67, 0x61,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31,
	0x1a, 0x2c, 0x73, 0x61, 0x67, 0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x67, 0x61, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70,
	0x0a, 0x16, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x61, 0x67,
	0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x4e, 0x0a, 0x17, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x61, 0x67,
	0x61, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x32, 0x86, 0x01, 0x0a, 0x14, 0x53, 0x61, 0x67, 0x61, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x2c, 0x2e, 0x73,
	0x61, 0x67, 0x61, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x73, 0x61, 0x67,
	0x61, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x65, 0x37, 0x36, 0x2f, 0x73, 0x61,
	0x67, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x73, 0x61, 0x67,
	0x61, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sagaprocessorapis_v1_processorapis_proto_rawDescOnce sync.Once
	file_sagaprocessorapis_v1_processorapis_proto_rawDescData = file_sagaprocessorapis_v1_processorapis_proto_rawDesc
)

func file_sagaprocessorapis_v1_processorapis_proto_rawDescGZIP() []byte {
	file_sagaprocessorapis_v1_processorapis_proto_rawDescOnce.Do(func() {
		file_sagaprocessorapis_v1_processorapis_proto_rawDescData = protoimpl.X.CompressGZIP(file_sagaprocessorapis_v1_processorapis_proto_rawDescData)
	})
	return file_sagaprocessorapis_v1_processorapis_proto_rawDescData
}

var file_sagaprocessorapis_v1_processorapis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sagaprocessorapis_v1_processorapis_proto_goTypes = []interface{}{
	(*ExecuteWorkflowRequest)(nil),  // 0: sagaprocessorapis.v1.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil), // 1: sagaprocessorapis.v1.ExecuteWorkflowResponse
	(*v1.Workflow)(nil),             // 2: sagatransactionapis.v1.Workflow
	(*v1.State)(nil),                // 3: sagatransactionapis.v1.State
}
var file_sagaprocessorapis_v1_processorapis_proto_depIdxs = []int32{
	2, // 0: sagaprocessorapis.v1.ExecuteWorkflowRequest.workflow:type_name -> sagatransactionapis.v1.Workflow
	3, // 1: sagaprocessorapis.v1.ExecuteWorkflowResponse.state:type_name -> sagatransactionapis.v1.State
	0, // 2: sagaprocessorapis.v1.SagaProcessorService.ExecuteWorkflow:input_type -> sagaprocessorapis.v1.ExecuteWorkflowRequest
	1, // 3: sagaprocessorapis.v1.SagaProcessorService.ExecuteWorkflow:output_type -> sagaprocessorapis.v1.ExecuteWorkflowResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sagaprocessorapis_v1_processorapis_proto_init() }
func file_sagaprocessorapis_v1_processorapis_proto_init() {
	if File_sagaprocessorapis_v1_processorapis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sagaprocessorapis_v1_processorapis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteWorkflowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sagaprocessorapis_v1_processorapis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteWorkflowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sagaprocessorapis_v1_processorapis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sagaprocessorapis_v1_processorapis_proto_goTypes,
		DependencyIndexes: file_sagaprocessorapis_v1_processorapis_proto_depIdxs,
		MessageInfos:      file_sagaprocessorapis_v1_processorapis_proto_msgTypes,
	}.Build()
	File_sagaprocessorapis_v1_processorapis_proto = out.File
	file_sagaprocessorapis_v1_processorapis_proto_rawDesc = nil
	file_sagaprocessorapis_v1_processorapis_proto_goTypes = nil
	file_sagaprocessorapis_v1_processorapis_proto_depIdxs = nil
}
