// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: workflowapis/v1/workflow.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SagaWorkflowServiceClient is the client API for SagaWorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaWorkflowServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type sagaWorkflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaWorkflowServiceClient(cc grpc.ClientConnInterface) SagaWorkflowServiceClient {
	return &sagaWorkflowServiceClient{cc}
}

func (c *sagaWorkflowServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/workflowapis.v1.SagaWorkflowService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaWorkflowServiceServer is the server API for SagaWorkflowService service.
// All implementations must embed UnimplementedSagaWorkflowServiceServer
// for forward compatibility
type SagaWorkflowServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedSagaWorkflowServiceServer()
}

// UnimplementedSagaWorkflowServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSagaWorkflowServiceServer struct {
}

func (UnimplementedSagaWorkflowServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedSagaWorkflowServiceServer) mustEmbedUnimplementedSagaWorkflowServiceServer() {}

// UnsafeSagaWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaWorkflowServiceServer will
// result in compilation errors.
type UnsafeSagaWorkflowServiceServer interface {
	mustEmbedUnimplementedSagaWorkflowServiceServer()
}

func RegisterSagaWorkflowServiceServer(s grpc.ServiceRegistrar, srv SagaWorkflowServiceServer) {
	s.RegisterService(&SagaWorkflowService_ServiceDesc, srv)
}

func _SagaWorkflowService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaWorkflowServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflowapis.v1.SagaWorkflowService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaWorkflowServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaWorkflowService_ServiceDesc is the grpc.ServiceDesc for SagaWorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaWorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflowapis.v1.SagaWorkflowService",
	HandlerType: (*SagaWorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _SagaWorkflowService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflowapis/v1/workflow.proto",
}
