apiVersion: v1
kind: Service
metadata:
  name: tracer
  labels:
    app: tracer
spec:
  clusterIP: None
  ports:
    - port: 50057
      name: tracer
  selector:
    app: tracer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracer
  labels:
    app: tracer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
      - name: tracer
        image: tracer
        ports:
        - containerPort: 50057
          protocol: TCP
          name: http