// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: sagahandlerapis/v1/handlerapis.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SagaHandlerServiceClient is the client API for SagaHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaHandlerServiceClient interface {
	HandleOperation(ctx context.Context, in *HandleOperationRequest, opts ...grpc.CallOption) (*HandleOperationResponse, error)
}

type sagaHandlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaHandlerServiceClient(cc grpc.ClientConnInterface) SagaHandlerServiceClient {
	return &sagaHandlerServiceClient{cc}
}

func (c *sagaHandlerServiceClient) HandleOperation(ctx context.Context, in *HandleOperationRequest, opts ...grpc.CallOption) (*HandleOperationResponse, error) {
	out := new(HandleOperationResponse)
	err := c.cc.Invoke(ctx, "/sagahandlerapis.v1.SagaHandlerService/HandleOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaHandlerServiceServer is the server API for SagaHandlerService service.
// All implementations must embed UnimplementedSagaHandlerServiceServer
// for forward compatibility
type SagaHandlerServiceServer interface {
	HandleOperation(context.Context, *HandleOperationRequest) (*HandleOperationResponse, error)
	mustEmbedUnimplementedSagaHandlerServiceServer()
}

// UnimplementedSagaHandlerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSagaHandlerServiceServer struct {
}

func (UnimplementedSagaHandlerServiceServer) HandleOperation(context.Context, *HandleOperationRequest) (*HandleOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleOperation not implemented")
}
func (UnimplementedSagaHandlerServiceServer) mustEmbedUnimplementedSagaHandlerServiceServer() {}

// UnsafeSagaHandlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaHandlerServiceServer will
// result in compilation errors.
type UnsafeSagaHandlerServiceServer interface {
	mustEmbedUnimplementedSagaHandlerServiceServer()
}

func RegisterSagaHandlerServiceServer(s grpc.ServiceRegistrar, srv SagaHandlerServiceServer) {
	s.RegisterService(&SagaHandlerService_ServiceDesc, srv)
}

func _SagaHandlerService_HandleOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaHandlerServiceServer).HandleOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagahandlerapis.v1.SagaHandlerService/HandleOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaHandlerServiceServer).HandleOperation(ctx, req.(*HandleOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaHandlerService_ServiceDesc is the grpc.ServiceDesc for SagaHandlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaHandlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sagahandlerapis.v1.SagaHandlerService",
	HandlerType: (*SagaHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleOperation",
			Handler:    _SagaHandlerService_HandleOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sagahandlerapis/v1/handlerapis.proto",
}
