apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: gateway-config
requires:
- path: ../../base
build:
  artifacts:
  - image: gateway
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: gateway
  port: 8081
  localPort: 9000
