apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: store-config
requires:
- path: ../../base
build:
  artifacts:
  - image: store
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: store
  port: 50055
  localPort: 9005