apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: state-config
requires:
- path: ../../base
build:
  artifacts:
  - image: state
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
